module.exports = {
  collectCoverageFrom: ['**/*.{ts,tsx,js,jsx}', '!**/node_modules/**'],
  projects: [
    'packages/animated-monaco/jest.config.js',
    'packages/animated-react-live/jest.config.js',
    'packages/animated-textarea/jest.config.js',
    'packages/curry/jest.config.js',
    'packages/get-number-precision/jest.config.js',
    'packages/icons/jest.config.js',
    'packages/paginate/jest.config.js',
    'packages/pagination/jest.config.js',
    'packages/range/jest.config.js',
    'packages/sleep/jest.config.js',
    'packages/string-splice/jest.config.js',
    'packages/times/jest.config.js',
    'packages/use-animate/jest.config.js',
    'packages/use-animated-diff/jest.config.js',
    'packages/use-paginate/jest.config.js',
    'packages/use-player/jest.config.js',
    'packages/use-selection-range/jest.config.js',
  ],
};
